SMaster/Controllers/Reports/ReportingFrequencyController.cs
using SMaster.Services;
using SMaster.Services.Sprints;
using SMaster.ViewModels.Dashboard;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SMaster.Controllers.Reports
{
    public class ReportingFrequencyController : Controller
    {
        private SprintPlanService _sprintPlanService;
        public ReportingFrequencyController()
        {
            _sprintPlanService = new SprintPlanService();
        }

        // GET: ReportingFrequency
        public ActionResult Index(DashboardListModel model)
        {
            model.LoadFrequency(_sprintPlanService);
            if (model.Export)
            {
                return UtilityService.ExportPartialToExcel(Response, PartialView("Partials/_PartialFrequency", model), "Staff Reporting Frequency");
            }

            return View(model);
        }
    }
}

SMaster/Views/ReportingFrequency/Index.cshtml
@model SMaster.ViewModels.Dashboard.DashboardListModel
@{
    ViewBag.Title = "Staff Frequency Of Reporting";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
    </ol>
</nav>

<div class="card card-default col-sm-12 no-padding" id="accordion">
    <div class="card-body" style="padding-bottom: 0.5rem;">
        @using (Html.BeginForm("Index", "ReportingFrequency"))
        {
            <div class="row">
                @Html.HiddenField("Success", "0")
                <div class="col-sm-2">
                    @Html.DropDownListWithLabelFor(m => m.Year, new SelectList(GenericLookupHelper.GetYears()), null, null)
                </div>
                <div class="col-sm-2">
                    @Html.DropDownListWithLabelFor(m => m.Month,
                                         new SelectList(GenericLookupHelper.GetMonthsOfYear(), "Value", "Key"), new { @class = "change-trigger-postback" }, null)
                </div>
                <div class="col-sm-3">
                    @Html.DropDownListWithLabelFor(m => m.UserId, new SelectList(LookupsHelper.GetUsers(), "Value", "Key"), new { @class = "validate-required" }, "-Select-")
                </div>
                <div class="col-sm-5 margin-top-20">
                    @Html.SubmitButton("Search", "pull-left margin-right-5")
                    @("|")
                    @Html.ActionLink("Clear", "Index", null, new { @class = "btn btn-info" })
                    @("|")
                    <a class="btn btn-success" href="@Url.Action("Index", Model.GetRouteValues(1, Model.StartDate, Model.EndDate, Model.UserId, true))" target="_blank">
                        <i class="fa fa-file-excel-o"> </i> Export To Excel
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        }
    </div>
</div>
<div class="clearfix"></div>

<div class="table-responsive no-padding margin-top-20">
    @Html.Partial("Partials/_PartialFrequency", Model)
</div>

<div class="clearfix"></div>
@section scripts{
    <script type="text/javascript">
        helper.controls.MENU_ID_TO_ACTIVATE = "menu-dashboard";
    </script>
}