SMaster/Controllers/Reports/ChargeableHoursController.cs
using SMaster.Services;
using SMaster.Services.Sprints;
using SMaster.ViewModels.Dashboard;
using SMaster.ViewModels.Reports;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SMaster.Controllers.Reports
{
    public class ChargeableHoursController : Controller
    {

        private SprintPlanService _sprintPlanService;
        public ChargeableHoursController()
        {
            _sprintPlanService = new SprintPlanService();
        }

        // GET: ChargeableHours
        public ActionResult Index(BillableHoursViewModel model)
        {
            if (model.Export == Enums.ExportMode.EXCEL)
            {
                model.LoadChargeableHours(_sprintPlanService);

                return UtilityService.ExportPartialToExcel(Response, PartialView("Partials/_partialChargeableHours", model), "Chargeable Hours");
            }
            else
            {
                model.LoadChargeableHours(_sprintPlanService);

                return View(model);
            }
        }

        public ActionResult PersonalInvoice(DashboardListModel model)
        {
            model.LoadFrequency(_sprintPlanService);
            if (model.Export)
            {
                return UtilityService.ExportPartialToExcel(Response, PartialView("Partials/_PersonalInvoice", model), "Personal Invoice");
            }
            return View(model);
        }

        public ActionResult ProjectExpenditure(BillableHoursViewModel model)
        {
            model.LoadExpenditure(_sprintPlanService);
            if (model.Export == Enums.ExportMode.EXCEL)
            {
                return UtilityService.ExportPartialToExcel(Response, PartialView("Partials/_PartialProjectHours", model), "Project Hours Worked");
            }
            else
            {
                return View(model);
            }
        }
    }
}

SMaster/Views/ChargeableHours/Index.cshtml
@model SMaster.ViewModels.Reports.BillableHoursViewModel

@{
    ViewBag.Title = "Chargeable Hours";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#"><i class="fa fa-bank"></i> Home</a></li>
        <li class="breadcrumb-item"><a href="#"><i class="fa fa-table"></i> Reports</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
    </ol>
</nav>

<div class="clearfix"></div>

<div class="card border-default col-sm-12 margin-top-20 margin-bottom-20 no-padding filter-panel">
    <div class="card-body">
        @using (Html.BeginForm("Index", "ChargeableHours"))
        {
            <div class="row">
                <div class="col-sm">
                    <div><label><b>Staff</b></label></div>
                    @Html.DropDownListFor(m => m.UserId, new SelectList(LookupsHelper.GetUserDetails(), "Value", "Key"), "-select-", new { @class = "related" })
                </div>
                <div class="col-sm">
                    @Html.TextBoxWithLabelFor(m => m.SearchTerm, new { @placeholder = "Search...", @maxlength = "30" })
                </div>
                <div class="col-sm">
                    <div><label><b>Start Date</b></label></div>
                    @Html.DatePickerWithoutLabelFor(m => m.StartDate)
                </div>
                <div class="col-sm">
                    <div><label><b>End Date</b></label></div>
                    @Html.DatePickerWithoutLabelFor(m => m.EndDate)
                </div>
                <div class="col-sm">
                    <div style="padding-top:20px">
                        @Html.SubmitButton("Search", "pull-left margin-right-5")
                        @Html.ActionLink("Reset Filters", "Index", null, new { @class = "btn btn-info pull-left" })
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        }
    </div>
</div>

<div style="margin-bottom: 10px;">
    <a class="btn btn-info" href="@Url.Action("Index", Model.GetRouteValues(1, SMaster.Enums.ExportMode.EXCEL))" target="_blank">
        <i class="fa fa-file-excel-o"></i> Export To Excel
    </a>
    @("|")
    <a href="@Url.Action("Index","ProjectResourceAnalysis", new { Model.StartDate, Model.EndDate, Model.UserId })" class="btn btn-warning"><i class="fa fa-money"></i> Generate Invoice </a>
    @("|")
    <a href="@Url.Action("PersonalInvoice","ProjectResourceAnalysis", new { Model.StartDate, Model.EndDate, Model.UserId })" class="btn btn-secondary"><i class="fa fa-clock-o"></i> View TimeSheets </a>
</div>

@Html.Partial("Partials/_partialChargeableHours", Model)

@section scripts{
    <script type="text/javascript">
        autocompleteCombo.initialize("UserId");
    </script>
}

SMaster/Views/ChargeableHours/PersonalInvoice.cshtml
@model SMaster.ViewModels.Dashboard.DashboardListModel
@{
    ViewBag.Title = "Personal Timesheet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#"><i class="fa fa-building"> </i> Home</a></li>
        <li class="breadcrumb-item"><a href="#"><i class="fa fa-table"> </i> Reports</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
    </ol>
</nav>

<div class="card card-default col-sm-12 no-padding" style="margin-bottom:10px" id="accordion">
    <div class="card-body" style="padding-bottom: 0.5rem;">
        @using (Html.BeginForm("PersonalInvoice", "ChargeableHours"))
        {
            @Html.HiddenFor(m => m.UserId)
            <div class="row">
                <div class="col-sm-2">
                    @Html.DropDownListWithLabelFor(m => m.Year, new SelectList(GenericLookupHelper.GetYears()), null, null)
                </div>
                <div class="col-sm-2">
                    @Html.DropDownListWithLabelFor(m => m.Month,
                                         new SelectList(GenericLookupHelper.GetMonthsOfYear(), "Value", "Key"), new { @class = "change-trigger-postback" }, null)
                </div>
                <div class="col-sm-3">
                    @Html.DropDownListWithLabelFor(m => m.UserId, new SelectList(LookupsHelper.GetUsers(), "Value", "Key"), new { @class = "validate-required" }, "-Select-")
                </div>
                <div class="col-sm-5 margin-top-20">
                    @Html.SubmitButton("Search", "pull-left margin-right-5")
                    @("|")
                    @Html.ActionLink("Clear", "Index", null, new { @class = "btn btn-info" })
                    @("|")
                    <a class="btn btn-success" href="@Url.Action("PersonalInvoice", Model.GetRouteValues(1, Model.StartDate, Model.EndDate, Model.UserId, true))" target="_blank">
                        <i class="fa fa-file-excel-o"> </i> Export To Excel
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        }
    </div>
</div>
<div class="clearfix"></div>
<a href="@Url.Action("PersonalInvoice","ChargeableHours", new { Model.StartDate, Model.EndDate, Model.UserId })" class="btn btn-warning"><i class="fa fa-money"></i> Generate Personal Invoice </a>

<div class="table-responsive no-padding" style="margin-top:10px">
    @Html.Partial("Partials/_PersonalInvoice", Model)
</div>

<div class="clearfix"></div>
@section scripts{
    <script type="text/javascript">
        helper.controls.MENU_ID_TO_ACTIVATE = "menu-dashboard";
    </script>
}

SMaster/Views/ChargeableHours/ProjectExpenditure.cshtml
@model SMaster.ViewModels.Reports.BillableHoursViewModel

@{
    ViewBag.Title = "Project Per Hour";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>@ViewBag.Title</h2>

<div class="clearfix"></div>

<div class="card border-default col-sm-12 margin-top-20 margin-bottom-20 no-padding filter-panel">
    <div class="card-body">
        @using (Html.BeginForm("ProjectExpenditure", "ChargeableHours"))
        {
            <div class="row">
                <div class="col-sm">
                    <div><label><b>Staff</b></label></div>
                    @Html.DropDownListFor(m => m.UserId, new SelectList(LookupsHelper.GetUserDetails(), "Value", "Key"), "-select-", new { @class = "related" })
                </div>
                <div class="col-sm">
                    @Html.TextBoxWithLabelFor(m => m.SearchTerm, new { @placeholder = "Search...", @maxlength = "30" })
                </div>
                <div class="col-sm">
                    <div><label><b>Start Date</b></label></div>
                    @Html.DatePickerWithoutLabelFor(m => m.StartDate)
                </div>
                <div class="col-sm">
                    <div><label><b>End Date</b></label></div>
                    @Html.DatePickerWithoutLabelFor(m => m.EndDate)
                </div>
                <div class="col-sm" >
                    <div style="padding-top:20px">
                        @Html.SubmitButton("Search", "pull-left margin-right-5")
                        @Html.ActionLink("Reset Filters", "ProjectExpenditure", null, new { @class = "btn btn-info pull-left" })
                    </div>
                    
                </div>
            </div>
            <div class="clearfix"></div>
        }
    </div>
</div>

<div style="margin-bottom: 10px;">
    <a class="btn btn-info" href="@Url.Action("ProjectExpenditure", Model.GetRouteValues(1, SMaster.Enums.ExportMode.EXCEL))" target="_blank">
        <i class="fa fa-file-excel-o"></i> Export To Excel
    </a>
</div>

@Html.Partial("Partials/_PartialProjectHours", Model)

@section scripts{
    <script type="text/javascript">
        autocompleteCombo.initialize("UserId");
    </script>
}