SMaster/Controllers/DashboardController.cs
using SMaster.Helpers;
using SMaster.Services;
using SMaster.Services.Sprints;
using SMaster.ViewModels.Dashboard;
using SMaster.ViewModels.Sprint;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SMaster.Controllers
{
    public class DashboardController : Controller
    {
        private SprintPlanService _sprintPlanService;
        private ProductService _productService;
        private NotificationService _notificationService;
        public DashboardController()
        {
            _sprintPlanService = new SprintPlanService();
            _productService = new ProductService();
            _notificationService = new NotificationService();
        }

        // GET: Dashboard
        public ActionResult Index(DashboardListModel model)
        {
            return View(model);
        }

        public ActionResult UnallocatedUsers(DashboardListModel model)
        {
            model.LoadUnallocatedUsers(_sprintPlanService);
            return View(model);
        }

        public ActionResult LevelOfEffortDetails(DashboardListModel model)
        {
            if (model.Export)
            {
                model.LoadWeeklyData(_sprintPlanService);

                return UtilityService.ExportPartialToExcel(Response, PartialView("Partials/_PartialTasks", model), "Weekly Report");
            }
            else
            {
                model.LoadWeeklyData(_sprintPlanService);

                return View(model);
            }
        }
        
        public ActionResult ProjectCost(DashboardListModel model)
        {
            if (model.Export)
            {
                model.LoadProjectCosting(_sprintPlanService);

                return UtilityService.ExportPartialToExcel(Response, PartialView("Partials/_PartialTasks", model), "Weekly Report");
            }
            else
            {
                model.LoadProjectCosting(_sprintPlanService);

                return View(model);
            }
        }

        public ActionResult ProjectPerUserCost(DashboardListModel model)
        {
            if (model.Export)
            {
                model.LoadProjectPerStaff(_sprintPlanService);

                return UtilityService.ExportPartialToExcel(Response, PartialView("Partials/_PartialTasks", model), "Weekly Report");
            }
            else
            {
                model.LoadProjectPerStaff(_sprintPlanService);

                return View(model);
            }
        }

        public ActionResult WeeklyReport(DashboardListModel model, int Success = 0)
        {
            if (model.Export)
            {
                model.LoadWeeklyData(_sprintPlanService);
                return UtilityService.ExportPartialToExcel(Response, PartialView("Partials/_PartialWeeklyReport", model), "Weekly Report");
            }
            else
            {
                model.LoadWeeklyData(_sprintPlanService);
                return View(model);
            }
        }

        public ActionResult SendReport(DateTime StartDate, DateTime EndDate)
        {
            _notificationService.PrepareNotification(StartDate, EndDate);
            return RedirectToAction("UsersLOEf");
        }

        public ActionResult UsersLOEf(DashboardListModel model)
        {
            if (model.Export)
            {
                model.LoadUsersLevelOfEffort(_sprintPlanService);

                return UtilityService.ExportPartialToExcel(Response, PartialView("Partials/_PartialLevelOfEffort", model), "Staff Level Of Effort");
            }
            else
            {
                model.LoadUsersLevelOfEffort(_sprintPlanService);

                return View(model);
            }
        }
    }
}

SMaster/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMaster.ViewModels;
using SMaster.Services;
using SMaster.Models;
using SMaster.Helpers;
using SMaster.Entities;
using SMaster.ViewModels.Products;
using SMaster.Models.Setups;

namespace SMaster.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Product
        private ProductService _productService;

        public ProjectController()
        {
            _productService = new ProductService();
        }
        
        public ActionResult Index(ProjectListModel model)
        {
            model.FilterProjects(_productService);

            return View(model);
        }
        
        public ActionResult View(int Id)
        {
            return View(_productService.GetProjects().Where(r => r.Id == Id).Single());
        }
        public ActionResult Details(int? Id)
        {
            var Data = (_productService.GetProjects().Where(r => r.Id == Id).SingleOrDefault() ?? new Project());

            return View(Data);
        }

        [HttpPost]
        public JsonResult Save(Project record)
        {
            return Json(new
            {
                Success = _productService.SaveProject(record),
                ErrorMessage = record.ErrorMessage
            });
        }

        public ActionResult Delete(int Id)
        {
            string ErrorMessage = null;

            _productService.Delete(Id, out ErrorMessage);

            return RedirectToAction("Index");
        }

        #region Partials

        [HttpPost]
        public PartialViewResult PartialClients()
        {
            return PartialView("Partials/_PartialClients", new ProjectClient());
        }

        #endregion
    }
}

SMaster/Controllers/ScrumController.cs
using SMaster.Entities;
using SMaster.Enums;
using SMaster.Helpers;
using SMaster.Models;
using SMaster.Models.Sprints;
using SMaster.Services;
using SMaster.Services.Sprints;
using SMaster.ViewModels.Sprint;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SMaster.Controllers
{
    public class ScrumController : Controller
    {
        private SprintPlanService _sprintService;
        private ProductService _productService;
        public ScrumController()
        {
            _sprintService = new SprintPlanService();
            _productService = new ProductService();
        }

        public ActionResult AllActivities(TaskListModel model, int Success = 0)
        {
            var LoggedUserName = User.Identity.Name;

            ViewBag.Success = Success;

            model.LoadData(_sprintService, _productService, ReportingType.DailyReporting);

            return View(model);
        }

        public ActionResult PendingActivities(TaskListModel model, int Success = 0)
        {
            model.IsReminder = true;

            var LoggedUserName = User.Identity.Name;

            ViewBag.Success = Success;
            model.BacessValidity();
            model.LoadData(_sprintService, _productService, ReportingType.AllPending);

            return View(model);
        }

        [HttpPost]
        public JsonResult SaveMyScrum(SprintTaskHistory MyCurrentTasks)
        {
            string ErrorMessage = null;

            return Json(new
            {
                Success = _sprintService.SaveDailyTask(MyCurrentTasks, out ErrorMessage, User.Identity.Name),
                ErrorMessage,
                DateToComplete=MyCurrentTasks.DateToComplete?.ToString("dd MMM yyyy")??""
            });
        }
    }
}

SMaster/Controllers/UsersController.cs
using SMaster.Helpers;
using SMaster.Service.ControlPanel;
using SMaster.ViewModels.Users;
using System.Linq;
using System.Web.Mvc;

namespace SMaster.Controllers
{
    [Authorize(Roles = SMasterUserManager.SuperRole)]
    public class UsersController : Controller
    {
        // GET: ControlPanel/Users

        private ControlPanelService _controlpanelService;

        public UsersController()
        {
            _controlpanelService = new ControlPanelService();
        }

        public ActionResult Index(UsersListViewModel model)
        {
            model.LoadData(_controlpanelService);

            return View(model);
        }

        public ActionResult Create()
        {
            return View(new NewUserViewModel());
        }

        [HttpPost]
        public ActionResult Create(NewUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                string ErrorMessage = null;

                if (_controlpanelService.CreateUser(model.UserName, model.Password, model.FirstName, model.LastName, model.OtherName, model.Email, model.IsActive
                    , model.Phone, model.UserRole, model.DailyRate, out ErrorMessage))
                {
                    return RedirectToAction("Index", new { SearchTerm = model.UserName});
                }

                model.ErrorMessage = ErrorMessage;
            }
            else
            {
                model.ErrorMessage = "Please fill all required fields!";
            }

            return View(model);
        }
        

        public ActionResult Details(string Id, int Success = 0)
        {
            return View((from a in _controlpanelService.GetUsers().Where(r => r.Id == Id)
                         from b in a.Roles
                         join c in _controlpanelService.GetUserRoles() on b.RoleId equals c.Id into JoinResult
                         from d in JoinResult.DefaultIfEmpty()
                         select new EditUserViewModel
                         {
                             Email = a.Email,
                             FirstName = a.FirstName,
                             LastName = a.LastName,
                             OtherName = a.OtherName,
                             Phone = a.PhoneNumber,
                             Initials = a.Initials,
                             UserName = a.UserName,
                             UserRole = d.Name,
                             DailyRate = a.DailyRate,
                             Id = a.Id,
                             IsActive = a.IsActive,
                         }).Single());
        }

        [HttpPost]
        public JsonResult UpdateDetails(EditUserViewModel model)
        {
            string ErrorMessage = null;
            bool Success = false;

            if (ModelState.IsValid)
            {
                if (_controlpanelService.UpdateUser(model.Id, model.FirstName, model.LastName, model.OtherName, model.Email, model.Initials, model.IsActive
                    , model.Phone, model.UserRole,model.DailyRate, out ErrorMessage))
                {
                    Success = true;
                }
            }
            else
            {
                ErrorMessage = "Please fill all required fields!";
            }

            return Json(new
            {
                Success,
                ErrorMessage
            });
        }

        [HttpPost]
        public JsonResult ResetPassword(string Id, string NewPassword)
        {
            string ErrorMessage = null;

            return Json(new
            {
                Success = _controlpanelService.ResetUserPassword(Id, NewPassword, out ErrorMessage),
                ErrorMessage = ErrorMessage
            });
        }
    }
}

SMaster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Scrum Master</title>
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        @@font-face {
    font-family: "Gotham C";
    src: url('@Url.Content("~/fonts/libelsuit.ttf")');
                }

        body{
    background-image:url('@Url.Content("~/Images/texture.jpg")');
        }

        /*.header-container{
    background-image:url('@Url.Content("~/Images/header-background-2.png")');
        }*/

.logo{
    margin-top:10px;
    margin-left:10px;
    background: transparent url("@Url.Content("~/Images/dc-logo.png")") no-repeat scroll 0px 0px;
    height: 60px;
    }
    </style>
</head>
<body onbeforeunload="showBusyDiv(true)">
    <div class="container">
        <div class="container">
            <div class="row margin-bottom-5">
                <div class="col-sm">
                    <div class="logo"></div>
                </div>
                <div class="col-sm-6 align-center title-main">
                    DataCare Scrum-Master
                    <div class="sub-title">Project Management Information Tool for agile development</div>
                </div>
                <div class="col-sm">
                    <div class="pull-right row" style="border: 1px solid #ccc;margin-right: 5%;border-radius: 5px;padding: 5px;background-color: #ede9e9;">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="col-sm">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    @Html.Partial("_LoginPartial")
                                }
                            </div>
                            <div class="col-sm">
                                <span class="pull-right">
                                    @(" | ")
                                    <strong><i><i class="fa fa-sign-out" style="color:#2a6496; margin-left:15px"></i> <a href="javascript:void(0)" onclick="document.getElementById('logoutForm').submit()">Log off</a></i></strong>
                                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                    {
                                        @Html.AntiForgeryToken()
                                    }
                                </span>
                            </div>
                        }
                        else
                        {
                            <div class="fa fa-lock login-icon pull-right"></div>
                        }
                    </div>
                </div>
            </div>
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <nav class="navbar navbar-expand-lg navbar-dark">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active" id="menu-home"><a class="nav-link" href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard"></i> Dashboard <span class="sr-only">(current)</span></a></li>
                        @if (User.IsInRole(SMasterUserManager.SuperRole) || User.IsInRole("Project Manager"))
                        {
                            <li class="nav-item" id="menu-project"><a class="nav-link" href="@Url.Action("Index", "Project")"><i class="fa fa-tasks"></i> Projects</a></li>
                        }
                        <li class="nav-item dropdown" id="menu-sprint">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-briefcase"></i>  Sprint Plan
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="@Url.Action("Index", "SprintPlan")"><i class="fa fa-tasks"></i> Sprint</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="@Url.Action("EditDetails", "SprintPlan", new { selectedType = SMaster.Enums.ReportingType.ExtraActivity })"> Extra Activities</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown" id="menu-scrum">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-tasks"></i>  Scrum
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="@Url.Action("AllActivities", "Scrum")">Daily Reporting</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="@Url.Action("PendingActivities", "Scrum")">OverDue Activities</a>
                            </div>
                        </li>
                        <li class="nav-item" id="menu-meetings"><a class="nav-link" href="@Url.Action("Index", "Meeting")"><span><i class="fa fa-calendar-check-o"></i>  Meetings Scheduler</span></a></li>
                        @if (!User.IsInRole(SMasterUserManager.REGULAR_USER))
                        {
                            <li class="nav-item dropdown" id="menu-dashboard">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-th-list"></i>   Reports
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="@Url.Action("ProjectCost", "Dashboard")">Completion Rate</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("UsersLOEf", "Dashboard")">Level of Effort</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("WeeklyReport", "Dashboard")">Weekly Report</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("UnallocatedUsers", "Dashboard")">Unallocated Users</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("Index", "ProjectCost")">Project Cost</a>
                                     <a class="dropdown-item" href="@Url.Action("Index", "ReportingFrequency")">Reporting Frequency</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("Index", "ChargeableHours")">Chargeable Hours</a>
                                    <a class="dropdown-item" href="@Url.Action("ProjectExpenditure", "ChargeableHours")">Project Per Hour</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SMasterUserManager.SuperRole))
                        {
                            <li class="nav-item" id="menu-users"><a class="nav-link" href="@Url.Action("Index", "Users")"><i class="fa fa-cogs"></i> Manage Users</a></li>
                        }
                    </ul>
                    @if (SMaster.Helpers.LookupsHelper.GetPending() > 0)
                    {
                        <form class="form-inline my-2 my-lg-0">
                            <a href="@Url.Action("PendingActivities", "Scrum")">
                                <button type="button" class="btn" style="background-image: linear-gradient(#007bff, #4177b4); color:#fff">
                                    Tasks Overdue <span class="badge badge-count"> : <span style="font-size:14px"> @SMaster.Helpers.LookupsHelper.GetPending() </span></span>
                                </button>
                            </a>
                        </form>
                    }
                </div>
            </nav>
        }
        <div class="body-content">

            <div class="actual-body">@RenderBody()</div>
        </div>
        <div class="align-center" id="busy-container">
            <div id="busy-div">
                <div class="fa fa-spinner fa-spin pull-left"></div>
                <div class="pull-left">
                    System busy....
                    <div id="busy-close-div"><a href="javascript:void(0)" onclick="hideBusyDiv()">Hide</a></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <footer>
            <div class="footer">&copy; @DateTime.Now.Year - Data Care (U) Ltd</div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/helpers")
    <script src="../Scripts/SMaster/highcharts.js"></script>
    <script src="../Scripts/SMaster/highcharts-3d.js"></script>
    <script src="../Scripts/SMaster/exporting.js"></script>

    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        helper.controls.SERVER_DATE_TODAY = new Date(@DateTime.Today.Year,@(DateTime.Today.Month-1),@DateTime.Today.Day);
        helper.controls.SERVER_DATE_LASTSEVEN = new Date(@DateTime.Today.Year,@(DateTime.Today.Month-1),@DateTime.Today.Day-7);
        $(function () {
            hideBusyDiv();
            helper.controls.initialize(true);
            $(".custom-breadcrumb a:last-of-type").addClass("active");
            helper.controls.postInitializationLogic();
        });
    </script>
    <script>
        function showBusyDiv(showCloseButton) {
            if (showCloseButton) {
                $("#busy-close-div").show();
            }
            else {
                $("#busy-close-div").hide();
            }
            $("#busy-container").show();
        }

        function hideBusyDiv() {
            $("#busy-container").hide();
        }
    </script>

    <script type="text/javascript">
        helper.controls.SERVER_DATE_TODAY = new Date(@DateTime.Today.Year,@(DateTime.Today.Month-1),@DateTime.Today.Day);

        $(function () {
            helper.controls.initialize();
        });

        function confirmFormSubmission(controlId){
            $("#"+controlId).closest("form").submit(function(){
                if(!$(this).valid()){
                    return false;
                }
                return confirm('Do you confirm saving these details?');
            });
        }

        $(document).ready(function () {

            // ANIMATEDLY DISPLAY THE NOTIFICATION COUNTER.
            $('#noti_Counter')
                .css({ opacity: 0 })
                .text('255')              // ADD DYNAMIC VALUE (YOU CAN EXTRACT DATA FROM DATABASE OR XML).
                .css({ top: '-10px' })
                .animate({ top: '-2px', opacity: 1 }, 500);

            $('#noti_Button').click(function () {

                // TOGGLE (SHOW OR HIDE) NOTIFICATION WINDOW.
                $('#notifications').fadeToggle('fast', 'linear', function () {
                    if ($('#notifications').is(':hidden')) {
                        $('#noti_Button').css('background-color', '#2E467C');
                    }
                    else $('#noti_Button').css('background-color', '#FFF');        // CHANGE BACKGROUND COLOR OF THE BUTTON.
                });

                $('#noti_Counter').fadeOut('slow');                 // HIDE THE COUNTER.

                return false;
            });

            // HIDE NOTIFICATIONS WHEN CLICKED ANYWHERE ON THE PAGE.
            $(document).click(function () {
                $('#notifications').hide();

                // CHECK IF NOTIFICATION COUNTER IS HIDDEN.
                if ($('#noti_Counter').is(':hidden')) {
                    // CHANGE BACKGROUND COLOR OF THE BUTTON.
                    $('#noti_Button').css('background-color', '#2E467C');
                }
            });

            $('#notifications').click(function () {
                return false;       // DO NOTHING WHEN CONTAINER IS CLICKED.
            });
        });
    </script>
</body>
</html>

SMaster/Views/Shared/_SetupLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SMaster</title>
    <style>
        @@font-face {
    font-family: "Gotham C";
    src: url('@Url.Content("~/fonts/libelsuit.ttf")');
                }

        body{        
    background-image:url('@Url.Content("~/Images/texture.jpg")');
        }

        .header-container{
    background-image:url('@Url.Content("~/Images/header-background-2.png")');
        }

.header-container .logo{
    background: transparent url("@Url.Content("~/Images/icons.png")") no-repeat scroll 0px 0px;
}
    </style>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container">
        <div class="header-container">

            <div class="logo"></div>
            <div class="title">
                <div class="title-main">OVC MBE</div>
                <div class="title-info">Program OVC Mapping and Beneficiary Enrollment Database</div>
            </div>

            @if (User.Identity.IsAuthenticated)
            {
                <div class="user-area pull-right">
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                    }
                    <div class="pull-left">Hello <b>@User.Identity.Name</b>!</div>
                    <div class="btn-group pull-right">
                        <a class="user-button dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i><i class="fa fa-caret-down"></i></a>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li>@Html.ActionLink("Manage Account", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                            <li>@Html.ActionLink("Manage Setups", "Setups", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                            <li class="divider"></li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    </div>
                    @*@Html.Partial("_LoginPartial")*@
                </div>
            }
            else
            {
                <div class="fa fa-lock login-icon pull-right"></div>
            }
        </div>
        @if (User.Identity.IsAuthenticated)
            {
            <div class="menu-top">
                <ul class="nav nav-pills">
                    <li id="menu-home"><a href="@Url.Action("Index","Home")">Home</a></li>
                    <li class="dropdown" id="menu-setup">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">
                            Setup <span class="fa fa-caret-down"></span>
                        </a>
                        <ul class="dropdown-menu">
                    
                            <li><a href="@Url.Action("Districts","Setup")">District</a></li>                          
                            <li><a href="@Url.Action("Subcounty","Setup")">Sub-County</a></li>
                            <li><a href="@Url.Action("Parishes", "Setup")">Parish</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("Regions","Setup")">Region</a></li>
                            <li><a href="@Url.Action("TSOs", "Setup")">TSOs</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("OrganisationType", "Setup")">Organisation Type</a></li>
                            <li><a href="@Url.Action("ThematicAreas", "ProviderService")">Thematic Area</a></li>
                            <li><a href="@Url.Action("SubThematicAreas", "ProviderService")">Sub-Thematic Area</a></li>
                            <li><a href="@Url.Action("OVCservices", "ProviderService")">OVC Services</a></li>
                            <li><a href="@Url.Action("TargetBeneficiaries", "ProviderService")">Beneficiary</a></li>

                        </ul>
                    </li>
                </ul>


            </div>
        }
        <div class="body-content">
            
            <div class="actual-body">@RenderBody()</div>
            <div class="clearfix"></div>
        </div>

        <footer>
            <div class="footer">&copy; @DateTime.Now.Year - Data Care (U) Ltd</div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/SMaster")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(function () {
            helper.controls.intialize();
        });
    </script>
</body>
</html>